config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products,            only: [:show]
    resources :categories,          only: [:show]

    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :single_product,            to: 'sample#single_product'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :including_master, -> { includes(master: [:images, :default_price]) }

  scope :related_products, ->(product) { joins(:taxons).including_master.where(spree_taxons: { id: product.taxons }).where.not(id: product.id).distinct }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @products = Spree::Product.in_taxon(@taxon).including_master
    @taxonomies = Spree::Taxonomy.includes(root: { children: :children })
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_LIMIT = 4

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = Spree::Product.related_products(@product).limit(RELATED_PRODUCTS_LIMIT)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout 'sample'

  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li>
              <a href="#">Body care</a>
            </li>
            <li>
              <a href="#">Chambray</a>
            </li>
            <li>
              <a href="#">Floral</a>
            </li>
            <li>
              <a href="#">Rejuvination</a>
            </li>
            <li>
              <a href="#">Shaving</a>
            </li>
            <li>
              <a href="#">Toilette</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li>
              <a href="#">Barbour</a>
            </li>
            <li>
              <a href="#">Brioni</a>
            </li>
            <li>
              <a href="#">Oliver Spencer</a>
            </li>
            <li>
              <a href="#">Belstaff</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li>
              <a href="#">Body care</a>
            </li>
            <li>
              <a href="#">Chambray</a>
            </li>
            <li>
              <a href="#">Floral</a>
            </li>
            <li>
              <a href="#">Rejuvination</a>
            </li>
            <li>
              <a href="#">Shaving</a>
            </li>
            <li>
              <a href="#">Toilette</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li>
              <a href="mailto:support@iamabdus.com">support@iamabdus.com</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go
              <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by
          <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li>
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-dribbble"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-vimeo"></i>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-tumblr"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="main-wrapper">

  <!-- HEADER -->
  <div class="header clearfix">

    <!-- TOPBAR -->
    <div class="topBar">
      <div class="container">
        <div class="row">
          <div class="col-md-6 hidden-sm hidden-xs">
            <ul class="list-inline">
              <li>
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-dribbble"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-vimeo"></i>
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="fa fa-tumblr"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-6 col-xs-12">
            <ul class="list-inline pull-right">
              <li>
                <span>
                  <a data-toggle="modal" href='#login'>Log in</a>
                  <small>or</small>
                  <a data-toggle="modal" href='#signup'>Create an account</a></span></li>
              <li class="dropdown searchBox">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-search"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <span class="input-group">
                      <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                      <span class="input-group-addon" id="basic-addon2">Search</span>
                    </span>
                  </li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-shopping-cart"></i>$0</a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>Item(s) in your cart</li>
                  <li>
                    <a href="#">
                      <div class="media">
                        <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                        <div class="media-body">
                          <h5 class="media-heading">INCIDIDUNT UT
                            <br>
                            <span>2 X $199</span></h5>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="media">
                        <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                        <div class="media-body">
                          <h5 class="media-heading">INCIDIDUNT UT
                            <br>
                            <span>2 X $199</span></h5>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <div class="btn-group" role="group" aria-label="...">
                      <button type="button" class="btn btn-default">Shopping Cart</button>
                      <button type="button" class="btn btn-default">Checkout</button>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- NAVBAR -->
    <nav class="navbar navbar-main navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><%= image_tag("img/logo.png", :alt => "") %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="index.html">Home</a>
            </li>
            <li class="dropdown megaDropMenu active">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
              <ul class="dropdown-menu row">
                <li class="col-sm-3 col-xs-12">
                  <ul class="list-unstyled">
                    <li>Products Grid View</li>
                    <li>
                      <a href="product_grid_left_sidebar.html">Products Sidebar Left</a>
                    </li>
                    <li>
                      <a href="product-grid-right-sidebar.html">Products Sidebar Right</a>
                    </li>
                    <li>
                      <a href="product-grid-3-col-filter.html">Products 3 Columns V1</a>
                    </li>
                    <li>
                      <a href="product-grid-3-col.html">Products 3 Columns V2</a>
                    </li>
                    <li>
                      <a href="product-grid-4-col.html">Products 4 Columns</a>
                    </li>
                  </ul>
                </li>
                <li class="col-sm-3 col-xs-12">
                  <ul class="list-unstyled">
                    <li>Products List View</li>
                    <li>
                      <a href="product_list_left_sidebar.html">Products Sidebar Left</a>
                    </li>
                    <li>
                      <a href="product-list-right-sidebar.html">Products Sidebar Right</a>
                    </li>
                    <li class="listHeading">Others</li>
                    <li class="active">
                      <a href="single_product.html">Single Product</a>
                    </li>
                    <li>
                      <a href="cart_page.html">Cart Page</a>
                    </li>
                  </ul>
                </li>
                <li class="col-sm-3 col-xs-12">
                  <ul class="list-unstyled">
                    <li>Checkout</li>
                    <li>
                      <a href="checkout_step_1.html">Step 1 - Address</a>
                    </li>
                    <li>
                      <a href="checkout_step_2.html">Step 2 - Shipping</a>
                    </li>
                    <li>
                      <a href="checkout_step_3.html">Step 3 - Payment</a>
                    </li>
                    <li>
                      <a href="checkout_step_4.html">Step 4 - Payment</a>
                    </li>
                    <li>
                      <a href="checkout_complete.html">Order Complete</a>
                    </li>
                  </ul>
                </li>
                <li class="col-sm-3 col-xs-12">
                  <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li>
                  <a href="about_us.html">About Us</a>
                </li>
                <li>
                  <a href="signup.html">Register</a>
                </li>
                <li>
                  <a href="signup-login.html">Register or Login</a>
                </li>
                <li>
                  <a href="login.html">Login</a>
                </li>
                <li>
                  <a href="lost-password.html">Password Recovery</a>
                </li>
                <li>
                  <a href="privacy_policy.html">Privacy Policy</a>
                </li>
                <li>
                  <a href="terms-and-conditions.html">Terms &amp; Conditions</a>
                </li>
                <li>
                  <a href="404.html">404 Not Found</a>
                </li>
                <li>
                  <a href="coming-soon.html">Coming Soon</a>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <a href="blog_right_sidebar.html">Right Sidebar</a>
                </li>
                <li>
                  <a href="blog_left_sidebar.html">Left Sidebar</a>
                </li>
                <li>
                  <a href="blog-fullwidth.html">Full Width</a>
                </li>
                <li>
                  <a href="blog-single-fullwidth.html">Single Post</a>
                </li>
                <li>
                  <a href="blog_single_right_sidebar.html">Single Right Sidebar</a>
                </li>
                <li>
                  <a href="blog_single_left_sidebar.html">Single Left Sidebar</a>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <a href="account-dashboard.html">Dashboard</a>
                </li>
                <li>
                  <a href="account-profile.html">Profile</a>
                </li>
                <li>
                  <a href="account-all-orders.html">All Orders</a>
                </li>
                <li>
                  <a href="account-single-order.html">Single Order</a>
                </li>
                <li>
                  <a href="account-wishlist.html">Wishlist</a>
                </li>
                <li>
                  <a href="account-address.html">Address</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
    </nav>

  </div>

</div>

app/views/layouts/_modals.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox">
              Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- PORODUCT QUICK VIEW MODAL -->
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("img/products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>$149</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">Size</option>
                <option value="1">Size 1</option>
                <option value="2">Size 2</option>
                <option value="3">Size 3</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="0">Qty</option>
                <option value="1">Qty 1</option>
                <option value="2">Qty 2</option>
                <option value="3">Qty 3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="#" class="btn btn-primary btn-block">Add to cart
                <i class="fa fa-angle-right" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:title) %> - BIGBAG Store</title>
    
    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script> <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> <![endif]-->

  </head>

  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/modals' %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/sample.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potepanec</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/potepan/categories/_categories_filter.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy-<%= taxonomy.id %>"><%= taxonomy.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="taxonomy-<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.root.children.each do |taxon| %>
                <% if taxon.children.empty? %>
                  <li>
                    <%= link_to potepan_category_path(taxon.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %><span>（<%= taxon.products.count %>）</span>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#taxon-<%= taxon.id %>"><%= taxon.name %>
                      <i class="fa fa-plus"></i>
                    </a>
                    <ul id="taxon-<%= taxon.id %>" class="collapse collapseItem" style="text-indent: 1em;">
                      <% taxon.children.each do |subtaxon| %>
                        <li>
                        <%= link_to potepan_category_path(subtaxon.id) do %>
                          <i class="fa fa-caret-right" aria-hidden="true"></i><%= subtaxon.name %>
                          <span>（<%= subtaxon.products.count %>）</span>
                        <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_colour_filter.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_price_filter.html.erb
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly="readonly">
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly="readonly">
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
    <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
  </div>
</div>

app/views/potepan/categories/_products.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <div class="productImage clearfix">
          <%= image_tag product.display_image.attachment(:product) %>
          <div class="productMasking">
            <ul class="list-inline btn-group" role="group">
              <li>
                <a data-toggle="modal" href=".login-modal" class="btn btn-default">
                  <i class="fa fa-heart"></i>
                </a>
              </li>
              <li>
                <a href="cart_page.html" class="btn btn-default">
                  <i class="fa fa-shopping-cart"></i>
                </a>
              </li>
              <li>
                <a class="btn btn-default" data-toggle="modal" href=".quick-view">
                  <i class="fa fa-eye"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="productCaption clearfix">
          <%= link_to potepan_product_path(product.id) do %>
            <h5><%= product.name %></h5>
          <% end %>
          <h3><%= product.display_price %></h3>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_size_filter.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_sorts.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'potepan/shared/light_header'%>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'categories_filter', taxonomies: @taxonomies %>
        <%= render 'price_filter' %>
        <%= render 'colour_filter' %>
        <%= render 'size_filter' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render 'sorts' %>
        <%= render 'products', products: @products %>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag product.display_image.attachment(:product) %>
            <div class="productMasking">
              <ul class="list-inline btn-group" role="group">
                <li>
                  <a data-toggle="modal" href=".login-modal" class="btn btn-default">
                    <i class="fa fa-heart"></i>
                  </a>
                </li>
                <li>
                  <a href="cart_page.html" class="btn btn-default">
                    <i class="fa fa-shopping-cart"></i>
                  </a>
                </li>
                <li>
                  <a class="btn btn-default" data-toggle="modal" href=".quick-view">
                    <i class="fa fa-eye"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="productCaption clearfix">
            <%= link_to potepan_product_path(product.id) do %>
              <h5><%= product.name %></h5>
            <% end %>
            <h3><%= product.display_price %></h3>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>